# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\dev\pynta\pynta\view\GUI\designer\adc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.FrequencyLabel = QtWidgets.QLabel(Form)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.FrequencyLabel)
        self.PointsLabel = QtWidgets.QLabel(Form)
        self.PointsLabel.setObjectName("PointsLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PointsLabel)
        self.UpdateButton = QtWidgets.QPushButton(Form)
        self.UpdateButton.setObjectName("UpdateButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.UpdateButton)
        self.ErrorLabel = QtWidgets.QLabel(Form)
        self.ErrorLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ErrorLabel)
        self.PointsSpinbox = QtWidgets.QSpinBox(Form)
        self.PointsSpinbox.setEnabled(True)
        self.PointsSpinbox.setKeyboardTracking(True)
        self.PointsSpinbox.setObjectName("PointsSpinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PointsSpinbox)
        self.FrequencySpinbox = QtWidgets.QSpinBox(Form)
        self.FrequencySpinbox.setObjectName("FrequencySpinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FrequencySpinbox)
        self.PlotView = PlotWidget(Form)
        self.PlotView.setObjectName("PlotView")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.PlotView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.FrequencyLabel.setText(_translate("Form", "Frequency"))
        self.PointsLabel.setText(_translate("Form", "points"))
        self.UpdateButton.setText(_translate("Form", "Update"))
from pyqtgraph import PlotWidget
