# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\dev\pynta\pynta\view\GUI\designer\signal_generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.WaveformLabel = QtWidgets.QLabel(Form)
        self.WaveformLabel.setObjectName("WaveformLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.WaveformLabel)
        self.WaveformSelector = QtWidgets.QComboBox(Form)
        self.WaveformSelector.setObjectName("WaveformSelector")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.WaveformSelector)
        self.FrequencyLabel = QtWidgets.QLabel(Form)
        self.FrequencyLabel.setObjectName("FrequencyLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.FrequencyLabel)
        self.FrequencySpinbox = QtWidgets.QDoubleSpinBox(Form)
        self.FrequencySpinbox.setObjectName("FrequencySpinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.FrequencySpinbox)
        self.AmplitudeLabel = QtWidgets.QLabel(Form)
        self.AmplitudeLabel.setObjectName("AmplitudeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.AmplitudeLabel)
        self.AmplitudeSpinbox = QtWidgets.QDoubleSpinBox(Form)
        self.AmplitudeSpinbox.setObjectName("AmplitudeSpinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.AmplitudeSpinbox)
        self.OffsetLabel = QtWidgets.QLabel(Form)
        self.OffsetLabel.setObjectName("OffsetLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.OffsetLabel)
        self.OffsetSpinbox = QtWidgets.QDoubleSpinBox(Form)
        self.OffsetSpinbox.setObjectName("OffsetSpinbox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.OffsetSpinbox)
        self.DutyCycleLabel = QtWidgets.QLabel(Form)
        self.DutyCycleLabel.setObjectName("DutyCycleLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.DutyCycleLabel)
        self.DutyCycleSpinbox = QtWidgets.QDoubleSpinBox(Form)
        self.DutyCycleSpinbox.setEnabled(True)
        self.DutyCycleSpinbox.setKeyboardTracking(True)
        self.DutyCycleSpinbox.setMaximum(100.0)
        self.DutyCycleSpinbox.setProperty("value", 50.0)
        self.DutyCycleSpinbox.setObjectName("DutyCycleSpinbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.DutyCycleSpinbox)
        self.UpdateButton = QtWidgets.QPushButton(Form)
        self.UpdateButton.setObjectName("UpdateButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.UpdateButton)
        self.ErrorLabel = QtWidgets.QLabel(Form)
        self.ErrorLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ErrorLabel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.WaveformLabel.setText(_translate("Form", "Waveform"))
        self.FrequencyLabel.setText(_translate("Form", "Frequency"))
        self.AmplitudeLabel.setText(_translate("Form", "Amplitude"))
        self.OffsetLabel.setText(_translate("Form", "Offset"))
        self.DutyCycleLabel.setText(_translate("Form", "Duty Cycle"))
        self.UpdateButton.setText(_translate("Form", "Update"))
